import Image from "next/image";

export const AppBackground = () => {
  return (
    <div className="fixed left-0 top-0 right-0 bottom-0 z-[-1]">
      <Image
        src="/assets/DALLE_space.png"
        alt="Space with planets and an astronaut coding on a laptop in space - Generated by AI - CHATGPT DALLE"
        className="object-cover object-center z-[-1]"
        fill={true}
        priority={true}
        quality={100}
      />
      <div className="fixed inset-0 bg-gradient-to-b from-transparent to-black z-[1] top-0 left-0 right-0 bottom-0"></div>
    </div>
  );
};

export default AppBackground;
