import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar_ from "./components/Navbar";
// import { DarkThemeToggle, Flowbite } from "flowbite-react";
// import { ThemeProvider } from "next-themes";
import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// https://www.youtube.com/watch?v=optD7ns4ISQ - dark theme
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <Flowbite> */}
      {/* <body className={`${inter.className} bg-white- bg-slate-900 text-white`}> */}
      <body>
        {/* <Navbar_ /> */}
        {/* <ThemeProvider>{children}</ThemeProvider> */}
        <Providers>{children}</Providers>
      </body>
      {/* </Flowbite> */}
    </html>
  );
}
