import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Navbar_ from "./components/Navbar";
// import { DarkThemeToggle, Flowbite } from "flowbite-react";
// import { ThemeProvider } from "next-themes";
import Providers from "./providers";
import ThemeSwitcher from "./components/ThemeSwitcher";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bartosz Swierzynski - Portfolio",
  description: "Generated by create next app",
};

// https://www.youtube.com/watch?v=optD7ns4ISQ - dark theme
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar_ />
        {/* <ThemeProvider>{children}</ThemeProvider> */}
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
      </body>
    </html>
  );
}
